import { defineConfig } from 'vite';
import { fileURLToPath } from 'url';
import laravel from 'laravel-vite-plugin';
import obfuscatorPlugin from 'rollup-plugin-obfuscator';

export default defineConfig({
    resolve: {
        alias: {
            'jquery':      fileURLToPath(new URL('./resources/js/shims/jquery.js',      import.meta.url)),
            'sweetalert2': fileURLToPath(new URL('./resources/js/shims/sweetalert2.js', import.meta.url)),
        },
    },
    plugins: [
        laravel({
            input: [
                'resources/css/app.css',
                'resources/js/app.js',
                'resources/js/announcementManagement.js',
                'resources/js/bookingTable.js',
                'resources/js/bookingTableManagement.js',
                'resources/js/budgetRelease.js',
                'resources/js/createPurchaseRequest.js',
                'resources/js/crmDashboard.js',
                'resources/js/employeeAttendance.js',
                'resources/js/employeePayslip.js',
                'resources/js/employeeSchedule.js',
                'resources/js/executivesDashboard.js',
                'resources/js/faqManagement.js',
                'resources/js/feedbackManagement.js',
                'resources/js/financeDashboard.js',
                'resources/js/financePayroll.js',
                'resources/js/financeSalesTransactions.js',
                'resources/js/governmentDiscountManagement.js',
                'resources/js/hrDashboard.js',
                'resources/js/hrEmployees.js',
                'resources/js/hrManage.js',
                'resources/js/hrPayroll.js',
                'resources/js/hrScheduleManager.js',
                'resources/js/inventoryAllItems.js',
                'resources/js/inventoryDashboard.js',
                'resources/js/inventoryProducts.js',
                'resources/js/kitchenDisplay.js',
                'resources/js/landingPage.js',
                'resources/js/landingPageAnnouncements.js',
                'resources/js/leaveApplication.js',
                'resources/js/leaveMngt.js',
                'resources/js/login.js',
                'resources/js/logout.js',
                'resources/js/manageSupplier.js',
                'resources/js/operationsDashboard.js',
                'resources/js/operationsSalesReporting.js',
                'resources/js/overtimeApplication.js',
                'resources/js/overtimeMngt.js',
                'resources/js/pointOfSale.js',
                'resources/js/procurementDashboard.js',
                'resources/js/purchaseOrders.js',
                'resources/js/purchaseRequest.js',
                'resources/js/recipeManagement.js',
                'resources/js/stockTransactions.js',
                'resources/js/supplier.js',
                'resources/js/supplierDashboard.js',
                'resources/js/supplierProducts.js',
                'resources/js/tableReservationManagement.js',
                'resources/js/utils/formatDateAndTime.js',
                'resources/js/utils/modal_builders_scm.js',
                'resources/js/utils/printPayslip.js',
                'resources/js/utils/reloadTable.js',
            ],
            refresh: true,
        }),
        obfuscatorPlugin({
            options: {
                compact: true,
                controlFlowFlattening: false,
                deadCodeInjection: false,
                stringArray: true,
                stringArrayEncoding: ['base64'],
                rotateStringArray: true,
            },
        }),
    ],
});
